### PR TITLE
move integration specs from submodule to local subtree

### PR DESCRIPTION
**Pull request by jpsim**
This would greatly simplify the spec updating process, while making it more accessible to new contributors. The biggest downside is that it adds weight to the repo.

Thoughts @segiddins @pcantrell @jverkoey?

### CODE REVIEW

**Comment by segiddins** [comment]
👎🏻 will makes PRs nearly impossible to review

**Comment by jverkoey** [comment]
Naive idea: could the spec files be stored in a file format that doesn't expand their content in the pull request interface?

**Comment by jpsim** [comment]
> will makes PRs nearly impossible to review

I disagree. It's important to be aware of the changes to the integration specs that a PR brings.

> Naive idea: could the spec files be stored in a file format that doesn't expand their content in the pull request interface?

This would likely also break git's ability to efficiently commit diffs to the repo, thus blowing up the repo size even more.

**Comment by jverkoey** [comment]
Ah I'd meant by simply setting a different file name, haha. The naive part was that I don't know how git chooses when to show a file's contents.

**Comment by jverkoey** [comment]
"File format" wasn't the correct wording.

**Comment by segiddins** [comment]
@jpsim this will mean even small code changes will be dwarfed by changes to the integration specs. I don't think that's worth it

**Comment by jverkoey** [comment]
Augh mobile apps are the worst. I meant how "github" chooses when...

**Comment by pcantrell** [comment]
I hate git submodules. Uuuuuggh. Half-baked, half broken, hard to work with, hard to work around when present. Certainly a pain point for new contributors.

Sam has a point, though.

PR diffs will be bad, especially at merge time. I don’t think the size of the repo is a big concern, but readability is. There's value in having the big delta filed separately — and if you _do_ want to see the changes associated with a PR, well, they’re only a click away on Github.

A few ideas, which I’m not necessarily advocating but just throwing out there as other options:

- Abandon submodules within the `integration_specs` repo, and keep only `specs/integration_specs` itself as a submodule. Removes some of the barriers to entry. (This is the first project I’ve been on where I really had to deal with subsubmodules, and it threw me at first.)
- Rework the `rebuild_integration_fixtures` rake task so that it takes care of some of the annoying git housekeeping (something along the lines of: scrub clean, check out master, force create branch named after parent repo branch if it’s not “master” and warn if it _is_ master, rebuild fixtures, commit but don’t push).
- Pare the fixtures down to a smaller, more carefully curated set of cases. Don’t make the full fixtures track every PR; instead, use them to periodically review changes at release time.

Again, not necessarily all good ideas, but perhaps worth considering.

**Comment by jpsim** [comment]
Ok, closing this because it's a worse solution than we have now.

Aaagh, controversy! *scuttles off and hides, away from confrontation*

**Comment by pcantrell** [comment]
> Aaagh, controversy!

Yeah. Debate always follows the questions with no good answers, and I think this is one such.

**Comment by esad** [comment]
Can we _please_ reconsider this. Every PR essentialy becomes two PRs that need to be merged in right order (first the spec changes need to get merged, then the original PR needs to be updated to point to the merged commit) so that CI can pass on the original PR.

**Comment by esad** [comment]
What we could at least fix is trying to keep jazzy master always point to the integration specs master commit. Right now this has diverged and it points to a branch called "add_siesta" with master far behind it.

**Comment by jpsim** [comment]
@esad sorry this has been problematic for you. It's made someone more manageable for people with commit access to both jazzy and the integration specs repo, since you just need to make the commit available on the later, no need for it to be in master.

You've been making great contributions towards jazzy in the last 2 months in my absence, so I'd love to give you commit access. I'm hoping to get back into jazzy work soon!

**Pull request closed without merging**
