### PR TITLE
Update development dependencies

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by jpsim** [comment]
I rebased this. Let's see what CI thinks. This is the last PR I want to include in 0.4.0.

**Comment by jpsim** [comment]
@segiddins looks like Moya doesn't build with CocoaPods 0.39.0.

**Comment by segiddins** [comment]
Looks like moya builds fine and its just a difference in execution output. I'll update that later

**Comment by jpsim** [comment]
There also something off with rubocop, it's trying to parse 2323 files?

```
Running RuboCop...
Inspecting 2323 files
.C.C.....C............WCCCCCCCCCCCCCCCCCCCC.CCCWWWWWWWWC.W.C.CCC...C.W.CC..CC.CCC.CC..WCW.CWWCCCWC....C.C.CW..CCC.CCCCC.WW...CCCC.CC.CWCCCW.CWC.CC....CCC.CWCCCC.CC..C.CC.C.C.CWW.CWCCCWCCCWCWCCCCCCW.WCCWWCCCCW.WWWCCCCC.CCCCWWC..CW.WWCWW.CCWW.CC.WCCWCWCWCCCCWCWWCWCWWCCW...CWC......C...WWCCWWCW...C..CC.C...WWWWWCCCCCCWWC..CCC.C.CCCCCCCCC..CCCCC.CCWCC.CCC.CC..CC.CCCC.CC.CCCCCC.CCC.CCCCCCCCCCCCCWCCCCCCCCCCCCCCCCCCCWC.C..CC..CCCCCC.CCC.C.C.CCCCCCCCWW.CCCCCC..CC.CC........C.C...C.C....W.CC.C.CCC.C.......C.............W........W..WCWCCW.WCCC.CCWCC..CWCCWCWWCCCCWCCC.WCW.WWCC.WWCWCWWWWCCWCWW.CW.CWCWCCWCCCCCCCWCCCWCCCCW.CCCCCCCCCCCCCCWCCCCCCCWCCCCCCWCCCCCWWC.CCCC.CCCCCCCCCCCCCWCCCC.WCCCWCCCWW.C....CCCWCCCWWCCCCCCCCWCWCWWCWWCCWWCCCCCWWWCCCWCWCCCCCCC.WCWWWWWWWWWWC.WWWWWWCWCCCCCCCWCCCCCWCCCCCCCCCCCCCCCCCCCCCCCCCCC.CCCCCCCCCC.CCWCCCWCCWWCCCCCCCWCCCCCCWWWWWWCWWWWWWWWWCWWWCWCCWWWWWWWCCCWCCCCCCCCCCWCWWCCCCCWCCCCCWCWCCWWCCCCCCCCCWWCCCCCCCCWCCCWCCCCCCCC.CCC.W.CCC.CCWC...CWC.WWCCWCW.CCCCCCCCCCCCCCCCC.CCC.WCWWCCCCCWCWCWCCCWWWCWW.WWWWCCW.CCWW.CCCCWCCC
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by segiddins** [comment]
Ah I can fix that

**Comment by jpsim** [comment]
@segiddins when do you think you'll be able to wrap this one up?

**Comment by segiddins** [comment]
Maybe after dinner tonight.

**Comment by segiddins** [comment]
@jpsim sorry, had a busy day. should be good now

**Comment by jpsim** [comment]
No problem at all! Moya is still failing though because malformed Xcode project warnings are being logged along with the date and time:

```diff
-2015-11-04 21:04:51.169 ruby[5855:26142] warning:  The file reference for "Alamofire.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
-2015-11-04 21:04:51.169 ruby[5855:26142] warning:  The file reference for "Alamofire.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
-2015-11-04 21:04:51.169 ruby[5855:26142] warning:  The file reference for "Moya.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
-2015-11-04 21:04:51.169 ruby[5855:26142] warning:  The file reference for "Moya.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
+2015-11-05 03:15:21.641 ruby[3128:6730] warning:  The file reference for "Alamofire.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
+2015-11-05 03:15:21.642 ruby[3128:6730] warning:  The file reference for "Alamofire.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
+2015-11-05 03:15:21.642 ruby[3128:6730] warning:  The file reference for "Moya.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
+2015-11-05 03:15:21.643 ruby[3128:6730] warning:  The file reference for "Moya.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
```

**Comment by segiddins** [comment]
Grrrr. I probably should fix that in CocoaPods, but it wouldn't really help here. Maybe just back out the CocoaPods update for now?

**Comment by jpsim** [comment]
I'd like to address the root of the problem here, which is that we're generating a malformed Xcode project starting with CocoaPods 0.39, where the project was fine before. See https://github.com/realm/jazzy-integration-specs/commit/a1148f85323da20457fe17a5414b0614546dbece

Or maybe the project has always been malformed, but CocoaPods 0.39 introduced a log for it?

**Comment by jpsim** [comment]
I've narrowed down the introduction of the malformed Xcode projects to some change between CocoaPods 0.39.0 betas 4 and 5: https://github.com/CocoaPods/CocoaPods/compare/0.39.0.beta.4...0.39.0.beta.5

**Comment by jpsim** [comment]
Alright, foregoing the CocoaPods update for the time being, until we can figure out why it's creating a malformed Xcode project with 0.39.0.

**Pull request merged**
