### PR TITLE
Fixed error when generating readme from podspec

### LINKED ISSUE #385: Undefined variable 'podspec' in readme_generator.rb
**Command:** jazzy 

**Trace:** 

```
`/Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/readme_generator.rb:34:in `generated_readme': undefined local variable or method `podspec' for Jazzy::ReadmeGenerator:Module (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/readme_generator.rb:13:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:196:in `document_index'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:297:in `document'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:82:in `block (2 levels) in build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:81:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:81:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:81:in `block in build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:92:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:92:in `block in each_doc'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:88:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:88:in `each_doc'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:77:in `build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:124:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:68:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'`
```

**Workaround:** Remove the podspec file.

### PR DESCRIPTION
**Pull request by pcantrell**
Fixes #385 (hopefully)

### CODE REVIEW

**Comment by pcantrell** [comment]
We’re not currently testing readmes generated from podspecs. Is it worth trying to add this to integration specs? Maybe put a phony podspec to misc_jazzy_features (although at that point we'd no longer be testing projects with no readme at all)?

**Comment by jpsim** [comment]
> We’re not currently testing readmes generated from podspecs.

Don't we do this for the Moya integration spec?

**Comment by segiddins** [comment]
Imho this is best covered by a unit test

**Comment by jpsim** [comment]
agreed. I was just thinking about that and how @segiddins and I initially thought about how to write tests for jazzy, and determined that integration specs would be a good first step, but that we should start adding unit tests shortly thereafter.

Like most temporary solutions, it's been temporary for for too long.

**Comment by pcantrell** [comment]
More case-specific / fine-grained tests seem like a decent idea.

What were you thinking the tested “units” would be? I’d be careful about coupling them too tightly to the existing class structure. It feels like it’s going to want refactoring as the project matures, and it would be nice if the tests were written so that the tests could validate that refactoring instead of having to change with it.

The ideal thing would be something that still treats the system sort of as a black box — “this structure produces these docs, however that happens” — but is (1) concise to write, (2) fast to run, and (3) can focus on a single code element instead of an entire project.

**Comment by pcantrell** [comment]
Should we just merge this to fix the associated issue? Good to figure out the testing strategy, but maybe not good to delay a 1-line fix for that.

**Comment by jpsim** [comment]
Yup, merge away!

**Pull request merged**
