### PR TITLE
[WIP] Swift 1.2

### PR DESCRIPTION
**Pull request by jpsim**
This adds proper support for Swift 1.2 to jazzy. This is a work-in-progress PR that I intend to split up once Swift 1.2 is officially shipped.

For now, this addresses #170, #185 & #186.

### CODE REVIEW

**Comment by segiddins** [comment]
@jpsim let me know when you want comments

**Comment by juangamnik** [comment]
I updated via `gem` to v0.1.6 and it says:

```bash
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.6/lib/jazzy/sourcekitten.rb:75:in `assert_swift_version': Jazzy only works with Swift 1.1. (RuntimeError)
```

How do I get a version that works with Swift 1.1 and Xcode 6.3.

**Comment by jpsim** [comment]
> How do I get a version that works with Swift 1.1 and Xcode 6.3.

Since Apple doesn't ship Swift 1.1 with Xcode 6.3 anymore, only Swift 1.2, that's not possible.

We'll be releasing a version of jazzy that works with Swift 1.2 in the coming days.

**Comment by juangamnik** [comment]
Sorry I misspelled this. I meant how can I get a version that works with Swift `1.2` and Xcode 6.3. As you can see in the error message, jazzy moans about my Swift 1.2 :smile:.

**Comment by juangamnik** [comment]
Sorry? I meant Swift 1.2. Jazzy 0.1.6 says: Swift 1.1, only. But I have Xcode 6.3 and Swift 1.2.

**Comment by cipriancaba** [comment]
Hi guys.. any new related to an update? 6.3 is officially out

**Pull request closed without merging**
