### PR TITLE
Group operators by name

### LINKED ISSUE #233: Separate operators from functions
Even though Swift operators are technically functions I think it would be useful to at least optionally list operators under their own heading. Especially in [this case](http://kareman.github.io/SwiftShell/) where there is a function `$` which now looks like an operator.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #233 
- [ ] Misc spec
- [ ] CHANGELOG

### CODE REVIEW

**Comment by istx25** [comment]
Merge conflicts need to be fixed and Travis :tenis:

**Comment by segiddins** [comment]
Someone needs to decide if we even want this first

**Comment by jpsim** [comment]
> Someone needs to decide if we even want this first

I'm not sure myself. It would help to see this in action. Maybe on a project with lots of custom operators? Like [thoughtbot/Argo](https://github.com/thoughtbot/Argo)?

**Comment by jpsim** [comment]
Thanks for the PR, Sam. I still think we need to improve how jazzy renders operators, but someone else needs to drive that exploration, and this PR hasn't progressed in the last year, so I'm closing this.

**Pull request closed without merging**
