### PR TITLE
Change Dash type for typedefs

### PR DESCRIPTION
**Pull request by Kapeli**
"Alias" was a bad idea 😦

### CODE REVIEW

**Comment by jpsim** [comment]
I agree with your take on this @Kapeli. Thanks! Can you rebuild the integration specs with this change, or shall I?

**Comment by Kapeli** [comment]
I have no idea how to rebuild them, so it's best if you do it 👍

**Comment by istx25** [comment]
Merge conflicts need to be resolved and integration specs rebuilt.

**Comment by jpsim** [comment]
I'll take care of this.

**Comment by jpsim** [comment]
Continuing in #685. Thanks @Kapeli!

**Pull request closed without merging**
