### PR TITLE
[Travis] Ignore new cocoapods version message

### PR DESCRIPTION
**Pull request by segiddins**
\c @jpsim

### CODE REVIEW

**Comment by jpsim** [comment]
This will still fail locally. Can you pass a command line argument to have cocoapods not print this?

**Comment by segiddins** [comment]
@jpsim not yet, but I've been thinking of making it an environment variable.

**Comment by segiddins** [comment]
@jpsim this is passing now, good to :shipit: ?

**Comment by jpsim** [comment]
Yes

**Pull request merged**
