### PR TITLE
Added support for Bitbucket repos - as opposed to gitHub

### PR DESCRIPTION
**Pull request by jeeftor**
I added the support for a 

```
-b --bitbucket_url
```

that will add a nice little picture (see below) and link for a bitbucket repo.  
- Added bitbucket image
- Updated mustache template
- Updated ruby files

screen shot 2015-10-08 at 10 15 32 am

**Note** - I updated this to Bit**b**ucket from Bit**B**ucket -> oops

### CODE REVIEW

**Comment by jpsim** [comment]
This is great, @jeeftor!

Taking a step back though, I think we can generalize things quite a bit by making the following changes:

1. `--github_url` -> `--project-url`
2. `--github-file-prefix` -> `--source-host-prefix`
3. `--source-host` with `github`, `bitbucket` & `gitlab` as options which would affect the ["View on GitHub"](https://github.com/realm/jazzy/blob/v0.3.1/lib/jazzy/templates/header.mustache#L4-L6) in the header and ["Show on GitHub"](https://github.com/realm/jazzy/blob/v0.3.1/lib/jazzy/templates/task.mustache#L60-L64) link in the declaration description

Thoughts on all this?

**Comment by jeeftor** [comment]
This is a much better plan ... think you guys want to tackle it? :) I'm happy to abandon this'll request - as i'm finding getting the travis stuff working a real pain (i did update the README.MD  however to add some testing lingo)

**Comment by jpsim** [comment]
Yes, I'm happy to tackle this generalization. I just saw your README additions, very nice! I'll be sure to include those as well.

**Comment by jeeftor** [comment]
Awesome!

**Comment by orta** [comment]
This willed a rebase

**Comment by jeeftor** [comment]
Any progress on this stuff?

**Comment by jpsim** [comment]
No, I haven't worked on this in quite some time, unfortunately. It's still something that should be done though, which is why I've kept this open.

**Comment by narlei** [comment]
Awesome!

**Comment by istx25** [comment]
Would we be able to close this PR and file another one with the README changes from @jeeftor and the code changes from @jpsim. Lmk.

**Comment by jeeftor** [comment]
Close it!!

**Comment by istx25** [comment]
Sounds good to me. Thanks @jeeftor!

**Pull request closed without merging**
