### PR TITLE
Support documenting "substructures" such as Extensions.

### PR DESCRIPTION
**Pull request by freak4pc**
This should resolve issue #502 where some documents didn't get recognised as being documented. 

This is due to the fact some more complex parts of code/documentation don't have a `key.doc.full_as_xml` property so they're being discarded as "undocumented", even though some of these have a `key.substructure` property which provides additional documentation information that should be considered.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for the PR @freak4pc!

Could you please [rebuild the integration specs](https://github.com/realm/jazzy/blob/a485292952693f6ce454b47a7553ad0145e8c649/Rakefile#L39-L70) and make a PR towards realm/jazzy-integration-specs against the [jp-sourcekitten-0.11.0 branch](https://github.com/realm/jazzy-integration-specs/compare/jp-sourcekitten-0.11.0) which is the most up-to-date branch. That'll make reviewing this easier as we'll be able to see exactly how this affects the build output.

Thanks again!

**Comment by freak4pc** [comment]
Just want to make sure since I'm not completely up to my Ruby game and dont really know how you guys work :) 

1. Rebuild the integration_specs subrepo
2. Send a pull request for the specific branch you discussed?

**Comment by freak4pc** [comment]
Done, I think :) Let me know if that suffices @jpsim

**Comment by jpsim** [comment]
Something went wrong. Try the following:

```
$ git submodule update --init --recursive
$ [sudo] gem install bundler
$ bundle install
$ bundle exec rake rebuild_integration_fixtures
```

**Comment by jpsim** [comment]
@freak4pc ok I just fixed the integration specs, upgrading all of them to their respective releases that use Swift 2.2. The integration specs on realm/jazzy-integration-specs should be up to date on `master`. Could you please rebase this branch, rebuild the integration specs and make a new PR towards realm/jazzy-integration-specs targeting the `master` branch? I know this is a bit of a convoluted process, so I apologize for that, and thank you for your continued work!

**Comment by freak4pc** [comment]
@jpsim It's all good, absolutely no worries! I love this project so It's my honour contributing what I can to it. 

I just pulled upstream, rebased, rebuilt the integration specs and will now try to send a PR of the integration specs again. I hope it's ok this time, if not - we'll move from there.

Thanks for your assistance !

**Comment by freak4pc** [comment]
Alright, re built the integration specs and pushed a PR :) let me know if there's anything needed on my side. Thanks !

**Comment by jpsim** [comment]
For starters, you'll need to update *this* repo to point to the updated branch, that way CI will pass (hopefully).

**Comment by jpsim** [comment]
Based on the changes in realm/jazzy-integration-specs#14, this seems right to me! So please update this repo to point to `a4df6bc` and this should be good assuming CI passes!

**Comment by freak4pc** [comment]
@jpsim Uhm I think I messed something up :) 
I just pulled master, rebased and added the specs commit on top. Am I missing anything?

**Comment by jpsim** [comment]
You're right that your rebase didn't quite work.

I did it myself here (https://github.com/realm/jazzy/compare/master...jp-freak4pc-substructure-extensions) and refactored the changes into a separate method, appeasing rubocop and rebuilding the integration specs along the way.

You can see the integration specs changes here: https://github.com/realm/jazzy-integration-specs/compare/master...jp-freak4pc-substructure-extensions

That diff highlights some issues with the implementation, specifically that the undocumented parent declarations are no longer being marked as undocumented. This will need to be fixed.

Feel free to continue your work on top of my `jp-freak4pc-substructure-extensions` branch.

**Comment by freak4pc** [comment]
Do you feel a change like this would be a sufficient fix? Since the file itself is documented, it seems just like the document abstract itself doesn't have documentation.

e.g. change
`declaration.abstract = Jazzy.markdown.render(doc['key.doc.comment'] || '')`

to
`declaration.abstract = Jazzy.markdown.render(doc['key.doc.comment'] || 'Undocumented')`

**Comment by freak4pc** [comment]
This does seem to produce the expected results. 
image

**Comment by freak4pc** [comment]
That one seems to be a rather quick fix but I also just noticed it creates some undocumented methods, when there are other documented ones in that file. I'm not sure if that's the expected behaviour... seems wrong but I'm not sure where the per-method-testing is being performed.

image

**Comment by jpsim** [comment]
I don't know what's happening there with `guard_check()` being undocumented and having an entirely wrong declaration. Does that happen just with your branch?

**Comment by freak4pc** [comment]
So, in the master version `UIView` extensions don't get documented *at all*. 

It seems the code that would consider if a specific method is documented or not might be mis-firing. I'm not sure exactly where it but this seems unrelated to the substructure fix, except for the fact it revealed it. 

Interesting though ...

image

**Comment by jpsim** [comment]
Ok. How do you think we should handle that @freak4pc?

**Comment by freak4pc** [comment]
I need to learn a bit more about the code structure since I already did this "in-point" fix I debugged for the substructures. It's kind of holiday season here so would be a bit tricky making time for this but I plan on tackling it in the following days hopefully :)

**Comment by freak4pc** [comment]
Haven't had any spare time to deal with this one (Wedding plans, ugh!) . 
If anyone wants to take it off my hands, be my guest.
Otherwise I can give this another go in about 3 weeks.

**Comment by istx25** [comment]
Hey @freak4pc! Thanks for the response. No worries. If it's your wedding, congrats! _If it's not, that'll be awkward haha 💃 _. We can wait. Looking forward to seeing progress on this in a few weeks. Cheers!

**Comment by freak4pc** [comment]
Indeed it is. Thanks @istx25 .

**Comment by johnfairh** [comment]
Closing because this was finished off in #825.

**Pull request closed without merging**
