### PR TITLE
Use Safe Filenames

### PR DESCRIPTION
**Pull request by SDGGiesbrecht**
Continuation from #700.

**Edit:** Integration specs are ready in realm/jazzy-integration-specs#23.

~~I don’t have the integration specs to match yet, but~~ @jpsim, you should look at my addition to `lib/jazzy/source_declaration/type.rb` below ~~before I do any more~~.

Is this a reasonable way to check the difference between an imported symbol and a manual, human‐language category?:

**[Edit]**

Currently checking whether something is an imported symbol by checking whether the identifier begins with `source`. This is the fragility I’m asking about.

Known Imported Symbols: 
Swift identifiers: `source.lang.swift...`
Objective‐C identifiers: `sourcekitten.source.lang.objc...`

Known Manual Identifiers:
Guides: `document.markdown`
Navigation Groups: `Overview`

**[End Edit]**

I don’t know the whole gamut of values `type.kind` is expected to have right now. What is there stopping a future `kind` from breaking the pattern and silently re‐introducing our bug for that new `kind`?

If this were Swift, I would use an enum and a switch statement with no default. Then future changes wouldn’t build without a matching update to that particular function. But I don’t really know what the Ruby solution is.

### CODE REVIEW

**Comment by SDGGiesbrecht** [comment]
This request is ready. Everything works as expected. Related tests are at realm/jazzy-integration-specs#23.

I’m waiting for someone to review the question [at the top](https://github.com/realm/jazzy/pull/702#issue-195440399).

(Because this has passed through several threads, I’ll restate here that the bug this fixes is #699.)

**Comment by SDGGiesbrecht** [comment]
@jpsim, I’m still waiting for your permission on this safe filename fix.

Besides your permission, everything is ready—tests and all.

**Comment by jpsim** [comment]
Yes, I appreciate it @SDGGiesbrecht. I still want to review this more thoroughly. Hoping to do that today. Please ping me again tomorrow if you haven't seen any feedback from me.

**Comment by SDGGiesbrecht** [comment]
Pinging you again “tomorrow” about filename safety, @jpsim. ☺

**Comment by jpsim** [comment]
This mostly looks good, but I'm a bit concerned about one thing, though it's probably unrelated to this PR...

When I merge `master` back into this branch and rebuild the integration specs, we lose a few parameters from the Siesta spec's docs:

```
diff --git a/document_siesta/after/api-docs/Classes/Resource.html b/document_siesta/after/api-docs/Classes/Resource.html
index 1c574ce..0fd0aee 100644
--- a/document_siesta/after/api-docs/Classes/Resource.html
+++ b/document_siesta/after/api-docs/Classes/Resource.html
@@ -740,29 +740,6 @@ up to you to canonicalize your parameter order.</p>
 <p>Note that, unlike load() and loadIfNeeded(), this method does <em>not</em> update latestData or latestError,
 and does not notify resource observers about the result.</p>
 
-<div class="aside aside-parameter">
-    <p class="aside-title">Parameter</p>
-    Parameter method: The HTTP verb to use for the request
-
-</div>
-
-<div class="aside aside-parameter">
-    <p class="aside-title">Parameter</p>
-    <p>Parameter requestMutation:
-An optional callback to change details of the request before it is sent. For example:</p>
-<pre class="highlight plaintext"><code>request(.POST) { nsreq in
-  nsreq.HTTPBody = imageData
-  nsreq.addValue(
-    "image/png",
-    forHTTPHeaderField:
-      "Content-Type")
-}
-</code></pre>
-
-<p>Does nothing by default.</p>
-
-</div>
-
```

**Comment by SDGGiesbrecht** [comment]
I just merged master into realm/jazzy-integration-specs#23.

Nothing changes outside of misc_jazzy_features. Inside it, there are [only additions](https://github.com/realm/jazzy-integration-specs/pull/23/files), (except a few lists that github registers as rearranged instead of just added to: `docSet.dsidx.csv`, `project.pbxproj` and `execution_output.txt`)

**Comment by SDGGiesbrecht** [comment]
I just updated from master.

**Comment by jpsim** [comment]
This PR no longer points to your updated integration fixtures, meaning that this new behavior is no longer tested.

**Comment by SDGGiesbrecht** [comment]
@jpsim, I don’t know how to point this request at the specs branch.

I’ve been testing them locally by switching branches within spec/integration_specs.

You’re instructions to me [here](https://github.com/realm/jazzy/pull/700#issuecomment-266872081) were:
> 5. Once that's merged to that repo's master branch, update this PR to point to the tip of master.

but if I merge the spec branch into that master, integration tests will fail for everyone else until this is merged to handle the new tests. Is that what you are asking me to do?

**Comment by 1ec5** [comment]
The Siesta changes are indeed unrelated to this PR. I noticed them before my recent PRs but left the diffs out because they looked unrelated. 😬

**Comment by jpsim** [comment]
Sorry for the confusion @SDGGiesbrecht, jazzy's integration specs as-a-submodule setup is a bit challenging to deal with. I've merged realm/jazzy-integration-specs#23 into `master` and will update this branch to point to the latest `master`, then once that passes CI this can be merged too.

**Comment by SDGGiesbrecht** [comment]
Thank you, @jpsim.

**Comment by jpsim** [comment]
Well crap. Looks like `unicode_normalize` is only available with later versions of Ruby:

```diff
-building site
-jam out ♪♫ to your fresh new docs in `docs`
+ROOT/lib/jazzy/sourcekitten.rb:102:in `sanitize_filename': undefined method `unicode_normalize' for "UndocumentedEnum":String (NoMethodError)
+	from ROOT/lib/jazzy/sourcekitten.rb:118:in `block in make_doc_urls'
+	from ROOT/lib/jazzy/sourcekitten.rb:113:in `each'
+	from ROOT/lib/jazzy/sourcekitten.rb:113:in `make_doc_urls'
+	from ROOT/lib/jazzy/sourcekitten.rb:120:in `block in make_doc_urls'
+	from ROOT/lib/jazzy/sourcekitten.rb:113:in `each'
+	from ROOT/lib/jazzy/sourcekitten.rb:113:in `make_doc_urls'
+	from ROOT/lib/jazzy/sourcekitten.rb:604:in `parse'
+	from ROOT/lib/jazzy/doc_builder.rb:142:in `build_docs_for_sourcekitten_output'
+	from ROOT/lib/jazzy/doc_builder.rb:76:in `build'
+	from ROOT/bin/jazzy:15:in `<main>'
```

Which is why this failed on Travis: https://travis-ci.org/realm/jazzy/builds/185953492

**Comment by SDGGiesbrecht** [comment]
I’ll take `unicode_normalize` out. It was not particularly important anyway. (It just shortened the illegible encoded sections.)

**Comment by SDGGiesbrecht** [comment]
I understand by
> once that passes CI this can be merged too.

that I have permission to merge this now that it [passes CI](https://travis-ci.org/realm/jazzy/builds/185961575#L875).

**Comment by SDGGiesbrecht** [comment]
Hurray! My documentation all works automatically now! Thanks for everything, @jpsim!

**Comment by jpsim** [comment]
Thanks for pushing this forward and closing addressed issues!

**Pull request merged**
