### PR TITLE
Swift SymbolGraph importer

### PR DESCRIPTION
**Pull request by johnfairh**
Swift 5.3 adds a new `symbolgraph-extract` function to generate declaration metadata directly from binary `.swiftmodule`s.  This PR teaches jazzy how to use the tool and generate regular docs from it.  It's either elegant or a Rube-Goldberg mess, generating SourceKit-style docs and feeding those into the existing code.

It works for system frameworks so you can do things like `jazzy -swift-build-tool symbolgraph -module Combine` to spit out jazzy docs for `Combine.framework`.

The symbolgraph-extract function is new and has a bunch of problems/limitations but is actively under development so should improve.

To try this out you need to have a swift 5.3 toolchain eg. Xcode 12, and do `jazzy --swift-build-tool symbolgraph --module Combine`.

### CODE REVIEW

**Comment by mikeKane** [comment]
Any idea's if/when this will merge?

**Comment by johnfairh** [comment]
Couple-three betas maybe?  The branch mostly works with Xcode 12b2 if you want to try it out.

**Comment by mikeKane** [comment]
> Couple-three more betas maybe? The branch mostly works with Xcode 12b2 if you want to try it out.

How can I checkout this branch?

**Comment by mikeKane** [comment]
This will not work if Objc is included? 

```
$ TOOLCHAINS=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain jazzy --swift-build-tool symbolgraph --module myModule.swiftmodule
Using config file .jazzy.yaml
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "PrivateHeaders/myModule.h"
        ^
/myModule/PrivateHeaders/myModule.h:20:9: error: 'myModule/PacketTunnelLogging.h' file not found
#import < myModule/PacketTunnelLogging.h>
        ^
<unknown>:0: error: could not build Objective-C module 'myModule
```

**Comment by johnfairh** [comment]
Added to tests and written some docs; this seems like a potentially useful thing, more so as the underlying tooling improves, so I plan to merge this and we can see if it finds any users.

**Comment by jpsim** [comment]
This is really cool! Should we cut a release with this?

**Comment by johnfairh** [comment]
Yep I plan to -- just want to poke at Xcode 12.2 first to see if anything needs fixing up.

**Pull request merged**
