### PR TITLE
Misc minor font size, weight, and color adjustments.

### PR DESCRIPTION
**Pull request by jverkoey**
Minor aesthetic change to bring the generated docs closer to the latest Apple documentation style.

Can understand if decisions were made regarding the css as it is and you'd prefer to keep it as is - will just port these changes into my own local css in that case.

### CODE REVIEW

**Comment by jverkoey** [comment]
Will need to update the integration_specs for this one as well.

**Comment by segiddins** [comment]
Can you share screenshots of the before/after?

**Comment by jverkoey** [comment]
### Before

before

### After

after

### UIKit

uikit

**Comment by jverkoey** [comment]
Will likely be easiest to click each photo and ctrl-tab between tabs :)

**Comment by jverkoey** [comment]
Meta-question: is the goal to match Apple's style as closely as possible? I made this pull request on the assumption that that is the case :)

**Comment by pcantrell** [comment]
I’d say these style changes improve readability.

Whether and how much Jazzy’s goal is to match the style of Apple’s docs is a question I’ll leave for @jpsim and @segiddins. Jazzy has struck out on its own in many of its _features_, but I’m not sure how much it wants to keep a separate _style_.

**Comment by segiddins** [comment]
I'm all for making jazzy output the best docs possible, deviating from apples only when it makes jazzy strictly better.

**Comment by orta** [comment]
I think it makes sense for Jazzy to aim at getting close-enough UI parity with the apple docs. Appledoc did the same too, that's generally what people are expecting when they use either of these tools.

**Comment by jpsim** [comment]
I agree with everyone's take on this, but Sam stole the words right out of my mouth:

> I'm all for making jazzy output the best docs possible, deviating from apples only when it makes jazzy strictly better.

**Comment by jpsim** [comment]
I'm all for these changes, you'll need to update the integration specs. You can push directly to that repo if you'd like, PRs aren't too important for that one. I usually always branch off the latest after running `bundle exec rake rebuild_integration_fixtures`.

**Comment by jpsim** [comment]
I'll take care of updating this.

**Comment by jpsim** [comment]
Closing in favor of #377. Thanks @jverkoey!

**Pull request closed without merging**
