### PR TITLE
Warning when USR ends with “ERR”

### PR DESCRIPTION
**Pull request by pcantrell**
Stops the next starry-eyed fool from filing a duplicate of #277.

### CODE REVIEW

**Comment by segiddins** [comment]
@pcantrell you're _on :fire:_ today! :+1:

**Comment by pcantrell** [comment]
Little one’s sleeping soundly, spouse is off at a birthday part, and I’ve got a coding itch.

But hey, you wrote the whole dang thing!

**Comment by jpsim** [comment]
This is pretty great, @pcantrell!

There are two things I'd suggest changing:

1. Instead of searching for `ERR` at the end of the USR, it'd be more appropriate to compare SourceKit's `key.typename` against `<<error type>>` (full string), since `ERR` could be anywhere in the USR and the sring `ERR` could be part of a legitimate type name.
2. The error message should suggest passing the same jazzy arguments to xcodebuild:

```
Please check for compile errors by running `xcodebuild` along with any arguments passed to jazzy's `-x` or `--xcodebuild-arguments`.
```

**Comment by pcantrell** [comment]
Done. I had to add `typename` to `SourceDeclaration`, which is a little bit confusing since that class already has a `type` property that probably really should be called `kind`.

I checked the error case that brought me here, and you’re quite right: the `ERR` suffix occurs always and only when the typename is `<<error type>>`. Out of curiosity, do we know for sure that will be the case? Does Apple actually document those SourceKit keys anywhere? Or are we just snooping and hoping?

**Comment by jpsim** [comment]
> Or are we just snooping and hoping?

Bingo! But it does make sense to me that if there's a single unknown component in a type, SourceKit treats the whole type as unknown.

Thanks again for the great PR!

**Pull request merged**
