### PR TITLE
support Objective-C module imports

### PR DESCRIPTION
**Pull request by jpsim**
Addresses #452. @rastersize could you please test this by running jazzy from source as described in our [README](https://github.com/realm/jazzy#development)?

### CODE REVIEW

**Comment by rastersize** [comment]
@jpsim I cloned this repo, checked out your branch and then ran `bundle install --path vendor/bundle`. Is that correct?

Because now I’m getting a different error, this time it seems as if the arguments sent to SourceKitten, alt. xcodebuild, are being mangled somehow.

```
Unrecognized arguments: "/Users/me/Project/include/Umbrella.h", -x, "objective-c", -soiryt, "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk", -I, "/Users/me/Project", -mfouldes
```

Command:
```
../jazzy/bin/jazzy \
    --sdk iphonesimulator \
    --objc \
    --umbrella-header include/Umbrella.h \
    --framework . \
    --source-directory . \
    --module ModuleName\
     --x --objc,/Users/me/Project/include/Umbrella.h,-x,objective-c,-isysroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk,-I,/Users/me/Project,-fmodules
```

**Comment by rastersize** [comment]
The Travis-CI build seems to confirm that it’s not me or my machine at least (phew :smile_cat:): https://travis-ci.org/realm/jazzy/builds/100938244#L3361

**Comment by jpsim** [comment]
> @jpsim I cloned this repo, checked out your branch and then ran `bundle install --path vendor/bundle`. Is that correct?

Yeah, although it shouldn't be necessary to pass `--path vendor/bundle`. Just `bundle install` should be fine.

**Comment by jpsim** [comment]
Huh, the string mangling is weird. Looks like something else is writing to STDOUT while `xcodebuild` is running. Will need some debugging.

**Comment by jpsim** [comment]
I'm a bit at a loss, because I can't find anything that changed that could account for asynchronous printing since the version of SourceKitten used in jazzy's main development branch and the new one this PR points to: https://github.com/jpsim/SourceKitten/compare/0ed186552d8f9f3e128ab382581102c55c2d3c73...26542b7251b3954978fb6ab64655303d85bb593b

**Comment by rastersize** [comment]
@jpsim I don’t see anything specific either :confused:

**Comment by rastersize** [comment]
@jpsim So I talked to a colleague today and the last argument looked like it could be an endian problem. As the characters are flipped in pairs of two, which suggest it could be a big/little endian problem.

But the mangling of `iosroot` looks much more weird so might not be that.

Also noticed that the SourceKitten bump had a bump of Commandant as well. Maybe there’s something there?

**Comment by jpsim** [comment]
It must be related to the bump in Commandant, although reading through its changes, I still can't pinpoint what's causing this. I think I'll have to revert back to the previous version.

**Comment by rastersize** [comment]
@jpsim Did you have any time to look into why the arguments to xcodebuild got so scrambled? No worries if you didn’t :smile_cat: 

I tested with 0.9.0 of SourceKitten just now together with the latest jazzy `master` and it has the same issue :crying_cat_face:

**Comment by jpsim** [comment]
@rastersize sorry for the very late reply, I just updated SourceKitten to 0.11.0, which has resolved the issue. I'd appreciate if you could try running jazzy from source again from this branch to see if it resolves your issues. Thanks!

**Comment by rastersize** [comment]
@jpsim no worries. Thanks for resolving it! I’m currently without computer, probably for the next week or so. Will test it as soon as I’m able to, sorry about that.

Do you have a link to the PR/commit that resolved the issue by the way. I’m curious as to what the underlying problem was :)

**Comment by jpsim** [comment]
> I’m currently without computer, probably for the next week or so. Will test it as soon as I’m able to, sorry about that.

Hey, it took me 2 months to get back to this, take your time! :wink: 

> Do you have a link to the PR/commit that resolved the issue by the way. I’m curious as to what the underlying problem was :)

This one, #496 and jpsim/SourceKitten#180.

**Pull request merged**
