### PR TITLE
Update Danger to 4.0

### PR DESCRIPTION
**Pull request by orta**
0.8 -> 4

GitHub updated their markdown renderer.

There's actually very few breaking changes to the Dangerfile, just that you need to prefix `git.` before a bunch of things.

### CODE REVIEW

**Comment by istx25** [comment]
Thanks @orta for filing this. Looks good to me. 😸

**Comment by segiddins** [comment]
Rebased

**Comment by orta** [comment]
ace 👍

**Comment by jpsim** [comment]
Travis is taking 18+ hours to process jobs, so I'll merge this under the assumption it works, since I want to cut a release and would like this in for future PRs sake.

Thanks all!

**Pull request merged**
