### PR TITLE
update SourceKitten to 0.11.0

### PR DESCRIPTION
**Pull request by jpsim**
This update picks up a buuuunch of previously missed docs: https://github.com/realm/jazzy-integration-specs/compare/skip-generation...jp-sourcekitten-0.11.0

I *think* those are all correct, and we're not mis-attributing docs, but I'd love if someone else could confirm too.

Not sure who's interested in reviewing this one /cc @pcantrell @segiddins

### CODE REVIEW

**Comment by jpsim** [comment]
Oh, I forgot the most important feature (other than finding the missing docs)!

SourceKitten 0.11.0 dynamically links `sourcekitd.framework` at runtime based on the `xcode-select -p` setting (among others). So we should be able to remove `xcinvoke` /cc @segiddins

**Comment by segiddins** [comment]
@jpsim not exactly, since xcinvoke chooses the correct Xcode from the swift version flag, which might not be the same as the selected Xcode.

**Comment by jpsim** [comment]
Yeah, except I'd much rather jazzy just respect the selected Xcode version, much like any other tool that either ships with Xcode or depends on it

**Comment by segiddins** [comment]
Up to you, but that's a breaking change from the current behavior.

**Comment by jpsim** [comment]
Thinking about this a bit more, I'd rather have the current behavior when a Swift version is explicitly requested, and the (new) default runtime linking behavior of SourceKitten otherwise. Thanks for the feedback @segiddins!

**Comment by jpsim** [comment]
Will do the update as part of #453. There should be no functional changes.

**Pull request closed without merging**
