### PR TITLE
[Config] Default to the selected Xcode version

### LINKED ISSUE #427: Use Xcode from `xcode-select` unless `--swift-version` is explicitly specified
Otherwise, users are understandably confused. See #426.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #427

### CODE REVIEW

**Comment by jpsim** [comment]
Awesome, thanks for this Sam! Care to add a changelog entry? It also looks as though the integration fixtures need to be updated, though that's unrelated to this change.

**Comment by jpsim** [comment]
I updated the integration specs, so all that's left here is a changelog entry

**Comment by segiddins** [comment]
Sorry, was away from my computer all afternoon.

**Comment by jpsim** [comment]
No problem at all! Time away from the computer's good for you 😉

**Pull request merged**
