### PR TITLE
Added support for access controls of fileprivate and open

### PR DESCRIPTION
**Pull request by shmuelk**
Description:
  - Modified the file lib/jazzy/source_declaration/access_control_level.rb to support the new access controls of fileprivate and open, available in very current Swift 3 drivers.     

Contributors:
  - https://github.com/shmuelk
    
Issues fixed:
  - #645 
  - #646

### CODE REVIEW

**Comment by pcantrell** [comment]
The code looks good to me.

The CI failure seems to be due only to Alamofire’s version changing. I’ll push a specs fix for that.

@shmuelk: You should credit yourself in the changelog!

**Comment by pcantrell** [comment]
Specs update. Travis should pass if you point this PR at ba8df1. Something like this, in case you aren't yet familiar with the joy of submodules:

    cd spec/integration_specs/
    git fetch
    git checkout ba8df1
    cd -
    git add spec/integration_specs
    git commit

…and push to your fork.

**Comment by shmuelk** [comment]
@pcantrell Thanks for the tip.

However the `git checkout ba8df1' fails with the message:

        error: pathspec 'ba8df1' did not match any file(s) known to git.

I looked in github and saw that the commit was ba8df10, I tried that and got the same failure.

**Comment by pcantrell** [comment]
Git accepts any initial string of a hash, so `git checkout ba8df1` and `git checkout ba8df10` should both work.

Its sounds like your integration_specs submodule isn't getting the latest commit when you fetch … for whatever reason. You try this nuclear option that I use when the specs get into a funky state:

    rm -rf spec/integration_specs
    git submodule update --init --recursive

If that works, then cd back into the specs directory and try it again:

    cd spec/integration_specs/
    git checkout ba8df1
    cd -
    git add spec/integration_specs
    git commit

(Note the two `cd` calls! You are checking out a commit of the specs submodule, not the main repo.)

**Comment by shmuelk** [comment]
@pcantrell Thanks for the more detailed suggestion. So far it looks better than before.

**Comment by pcantrell** [comment]
Yeah, just down to Rubocop warnings. You can check those locally with `rake rubocop`.

It’s complaining that you either need to have just a single space on each side of `=`, or make all the equal signs line up. This is a spot where aligned `=` reads much better IMO, but that pushes it to an 86-char line.

@jpsim: How would you feel about switching Rubocop to a max line length of 100 instead of 80 project-wide? The 80-column limit is often a pain point for me trying to format code in Jazzy; it feels a bit tight in 2016. (My own projects I keep ~120 these days.)

**Comment by pcantrell** [comment]
Looking good! Thanks for the contribution — and for bearing with all the metawork.

**Comment by jpsim** [comment]
> How would you feel about switching Rubocop to a max line length of 100 instead of 80 project-wide? The 80-column limit is often a pain point for me trying to format code in Jazzy; it feels a bit tight in 2016. (My own projects I keep ~120 these days.)

👍 💯 I'm all for it

**Pull request merged**
